### ISSUE TITLE
Rebuild fails against Node v0.12..0

### ISSUE THREAD

**Issue by erhhung** [GritDesign/node-jpegorientation#3]
I just upgraded my Node from 0.10.36 to 0.12.0 and ran `npm rebuild`. I'm now getting all sorts of errors. Is this a known issue or do I need to upgrade other dependencies (on OS X 10.10.2)? I'll downgrade Node for now.

```
> jpegorientation@1.0.2 install /Users/erhhung/Projects/server/node_modules/jpegorientation
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/jpegexiforient/src/jpegexiforient.o
../src/jpegexiforient.cc:70:24: error: unknown type name 'uv_work_t'
void OrientationWorker(uv_work_t* req)
                       ^
../src/jpegexiforient.cc:76:23: error: unknown type name 'uv_work_t'
void OrientationAfter(uv_work_t* req)
                      ^
../src/jpegexiforient.cc:78:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/erhhung/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/jpegexiforient.cc:85:15: error: no matching function for call to 'Undefined'
    argv[1] = Undefined();
              ^~~~~~~~~
/Users/erhhung/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not viable:
      requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/jpegexiforient.cc:88:48: error: no member named 'New' in 'v8::String'
        argv[0] = Exception::TypeError(String::New("Could not open source file"));
                                       ~~~~~~~~^
../src/jpegexiforient.cc:91:48: error: no member named 'New' in 'v8::String'
        argv[0] = Exception::TypeError(String::New("Premature End of JPEG file"));
                                       ~~~~~~~~^
../src/jpegexiforient.cc:94:48: error: no member named 'New' in 'v8::String'
        argv[0] = Exception::TypeError(String::New("Invalid Exif data"));
                                       ~~~~~~~~^
../src/jpegexiforient.cc:97:48: error: no member named 'New' in 'v8::String'
        argv[0] = Exception::TypeError(String::New("Unknown fatal error"));
                                       ~~~~~~~~^
../src/jpegexiforient.cc:101:15: error: no matching function for call to 'Undefined'
    argv[0] = Undefined();
              ^~~~~~~~~
/Users/erhhung/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not viable:
      requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/jpegexiforient.cc:102:43: error: too few arguments to function call, expected 2, have 1
    argv[1] = Integer::New(request->result);    
              ~~~~~~~~~~~~                ^
/Users/erhhung/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/jpegexiforient.cc:107:20: error: member reference type 'Persistent<v8::Function>' is not a
      pointer; maybe you meant to use '.'?
  request->callback->Call(Context::GetCurrent()->Global(), 2, argv);
  ~~~~~~~~~~~~~~~~~^~
                   .
../src/jpegexiforient.cc:107:22: error: no member named 'Call' in 'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
  request->callback->Call(Context::GetCurrent()->Global(), 2, argv);
  ~~~~~~~~~~~~~~~~~  ^
../src/jpegexiforient.cc:107:36: error: no member named 'GetCurrent' in 'v8::Context'
  request->callback->Call(Context::GetCurrent()->Global(), 2, argv);
                          ~~~~~~~~~^
../src/jpegexiforient.cc:114:21: error: no member named 'Dispose' in 'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
  request->callback.Dispose();
  ~~~~~~~~~~~~~~~~~ ^
../src/jpegexiforient.cc:122:21: error: no member named 'AsciiValue' in 'v8::String'
        v8::String::AsciiValue string(value);
        ~~~~~~~~~~~~^
../src/jpegexiforient.cc:123:37: error: use of undeclared identifier 'string'
        char *str = (char *) malloc(string.length() + 1);
                                    ^
../src/jpegexiforient.cc:124:22: error: use of undeclared identifier 'string'
        strcpy(str, *string);
                     ^
../src/jpegexiforient.cc:132:44: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
static Handle<Value> JpegOrientation(const Arguments& args)
                                           ^~~~~~~~~
                                           v8::internal::Arguments
/Users/erhhung/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
      declared here
class Arguments;
      ^
../src/jpegexiforient.cc:134:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/erhhung/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/jpegexiforient/src/jpegexiforient.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/erhhung/Projects/server/node_modules/jpegorientation
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

**Comment by paleite** [comment]
I have the exact same problem. Any update on this? Thanks in advance :smiley:

**Comment by alex88** [comment]
no updates?

**Comment by e-monson** [comment]
Same here.

**Comment by hendrawd** [comment]
I exactly have the same problem and it is a legacy code from my ex co-worker. Isn't there any update or solution for this?
